/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const DynamicErrorRouteLazyImport = createFileRoute('/dynamic-error')()
const IndexRouteLazyImport = createFileRoute('/')()
const DynamicIdRouteLazyImport = createFileRoute('/dynamic/$id')()
const DynamicErrorIdRouteLazyImport = createFileRoute('/dynamic-error/$id')()
const DynamicIndexRouteLazyImport = createFileRoute('/dynamic/')()

// Create/Update Routes

const DynamicErrorRouteLazyRoute = DynamicErrorRouteLazyImport.update({
  path: '/dynamic-error',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dynamic-error/route.lazy').then((d) => d.Route),
)

const IndexRouteLazyRoute = IndexRouteLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index/route.lazy').then((d) => d.Route))

const DynamicIdRouteLazyRoute = DynamicIdRouteLazyImport.update({
  path: '/dynamic/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dynamic/$id/route.lazy').then((d) => d.Route),
)

const DynamicErrorIdRouteLazyRoute = DynamicErrorIdRouteLazyImport.update({
  path: '/$id',
  getParentRoute: () => DynamicErrorRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dynamic-error/$id/route.lazy').then((d) => d.Route),
)

const DynamicIndexRouteLazyRoute = DynamicIndexRouteLazyImport.update({
  path: '/dynamic/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dynamic/index/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/dynamic-error': {
      preLoaderRoute: typeof DynamicErrorRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/dynamic/': {
      preLoaderRoute: typeof DynamicIndexRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/dynamic-error/$id': {
      preLoaderRoute: typeof DynamicErrorIdRouteLazyImport
      parentRoute: typeof DynamicErrorRouteLazyImport
    }
    '/dynamic/$id': {
      preLoaderRoute: typeof DynamicIdRouteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRouteLazyRoute,
  DynamicErrorRouteLazyRoute.addChildren([DynamicErrorIdRouteLazyRoute]),
  DynamicIndexRouteLazyRoute,
  DynamicIdRouteLazyRoute,
])

/* prettier-ignore-end */
